#!/usr/bin/env node

/**
 ****************************************************************************
 * Copyright 2017 Jonathan Barronville <jonathan@belairlabs.com>            *
 *                                                                          *
 * Licensed under the Apache License, Version 2.0 (the "License");          *
 * you may not use this file except in compliance with the License.         *
 * You may obtain a copy of the License at                                  *
 *                                                                          *
 *     http://www.apache.org/licenses/LICENSE-2.0                           *
 *                                                                          *
 * Unless required by applicable law or agreed to in writing, software      *
 * distributed under the License is distributed on an "AS IS" BASIS,        *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. *
 * See the License for the specific language governing permissions and      *
 * limitations under the License.                                           *
 ****************************************************************************
 */

const childProcess = require('child_process')
const fs = require('fs')
const path = require('path')

const LOGGING_PREFIX = '[tools/watch-build-src]'
const ROOT_DIRECTORY = path.join(__dirname, '..')
const SRC_DIRECTORY = path.join(ROOT_DIRECTORY, 'src')

console.info(`${LOGGING_PREFIX}: Starting file watcher …`)

fs.watch(SRC_DIRECTORY, {
  encoding: 'utf8',
  persistent: true,
  recursive: true
}, (eventType, fileName) => {
  if (fileName !== null) {
    console.info(`${LOGGING_PREFIX}: File "${
      path.join('src', fileName)
    }" updated … triggering build script.`)
  } else {
    console.info(`${LOGGING_PREFIX}: File updated … triggering build script.`)
  }

  childProcess.spawn('npm', ['run', 'build-src'], {
    cwd: ROOT_DIRECTORY,
    env: process.env
  })
})
